# Generated by Django 4.2.4 on 2023-08-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_our_services_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_services',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
