# Generated by Django 4.2.4 on 2023-08-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_services',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='website.category'),
        ),
    ]
